---
include:
  - project: claranet/guildes/pipeline/helpers
    ref: v4.13.5
    file: tool_versions.yml

variables:
  KUBERNETES_MEMORY_REQUEST: "600Mi"
  KUBERNETES_MEMORY_LIMIT: "1Gi"
  KUBERNETES_CPU_REQUEST: "1"

stages:
  - lint
  - unit-test

lint:
  stage: lint
  image: python:${PYTHON_VERSION}
  needs:
    - "tool versions"
  script:
    - pip install uv==${UV_VERSION}
    - uv run tox -e lint

tox:
  stage: unit-test
  image: python:${PYTHON_TEST_VERSION}
  needs:
    - "tool versions"
  parallel:
    matrix:
      - PYTHON_TEST_VERSION: ["3.10", "3.11", "3.12", "3.13", "3.14"]
  script:
    - pip install uv==${UV_VERSION}
    - uv run tox -e coverage
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  coverage: '/^TOTAL.+?(\d+\%)$/'
